words = [  # 2000 ta
    "salom", "ajoyib", "daraxt", "kitab", "uy", "bola", "qiz", "ota", "ana", "aka",
    "uka", "daryo", "maktab", "deraza", "eshik", "kursi", "stul", "sumka", "ruchka",
    "defter", "rang", "yashil", "sariq", "qizil", "moviy", "yaxshi", "yoman", "katta",
    "kichik", "tez", "sekin", "ertalab", "tun", "kun", "hafta", "yil", "yangi",
    "eski", "baland", "past", "shirin", "achchiq", "suv", "non", "chay", "qand",
    "asal", "meva", "olma", "banan", "anjir", "shaftali", "tarvuz", "sabzi", "piyaz",
    "sut", "idish", "raqam", "matn", "soz", "gap", "saval", "javab", "yuz", "bosh",
    "kul", "til", "tish", "ruh", "dil", "quloq", "burun", "qalam", "uychi", "sinf",
    "oina", "sham", "nur", "yulduz", "osman", "yer", "dara", "bahar", "yoz", "kuz",
    "qish", "yomir", "bulut", "havo", "saxna", "rasa", "kitabxan", "ustoz", "talaba",
    "do‘st", "dars", "ish", "pul", "savdo", "uyin", "kitabcha", "uychi"
    "bahar", "yoz", "kuz", "qish", "havo", "yer", "quyash", "yomir", "bulut", "shamol",
    "qum", "tuproq", "daryo", "ariq", "ko‘l", "deniz", "tosh", "tabaqat", "tep", "dara",
    "barg", "sham", "yulduz", "tun", "ertalab", "kecha", "kun", "hafta", "yil", "asr",
    "qalamcha", "chiz", "rasm", "chizma", "yozuv", "matn", "parcha", "she’r", "hikaya", "maqala",
    "ustun", "devor", "parda", "soat", "telefon", "noutbuk", "stul", "kursi", "divan", "karav",
    "balandlik", "pastlik", "tezlik", "sokinlik", "baxt", "quvonch", "yig‘i", "kulgu", "dil", "ruh",
    "yurak", "bosh", "qo‘l", "oyaq", "bel", "tirsak", "tizza", "barmak", "tirnak", "bo‘yin",
    "qorin", "belanchak", "stakan", "piyala", "chashka", "kitab", "defter", "sumka", "ruchka", "tizza",
    "oina", "deraza", "eshik", "devor", "uyn", "xarita", "rasm", "shar", "belgi", "raqam",
    "son", "tartib", "bir", "ikki", "uch", "turt", "besh", "alt", "yetti", "sakiz"
     "aka", "uka", "opa", "singil", "ota", "ana", "bola", "qiz", "yigit", "erkak",
    "ayal", "ustoz", "talaba", "dars", "kitab", "defter", "ruchka", "qalam", "sumka", "piyala",
    "idish", "stul", "kursi", "stol", "karav", "divan", "parda", "deraza", "eshik", "uyn",
    "xon", "burchak", "devor", "tavan", "zamin", "xarita", "rasm", "chizma", "yozuv", "matn",
    "parcha", "maqala", "hikaya", "she’r", "sat", "satr", "soat", "daqiqa", "sekund", "hafta",
    "kun", "tun", "ertalab", "kecha", "yil", "asr", "bahar", "yoz", "kuz", "qish",
    "havo", "yer", "quyash", "yomir", "bulut", "shamol", "qum", "tuproq", "daraxt", "barg",
    "meva", "sabzi", "piyaz", "tarvuz", "olma", "banan", "shaftali", "anjir", "nok", "behi",
    "shakar", "asal", "non", "sut", "chay", "suv", "qaynatma", "ta’m", "taom", "osh",
    "idish", "chashka", "tabaqa", "vilka", "qosik", "pichak", "bel", "bosh", "yuz", "ko‘z",
    "quloq", "burun", "til", "tish", "yurak", "ruh", "dil", "qalb", "oyaq", "qo‘l",
    "tirsak", "barmak", "tirnak", "tizza", "bo‘yin", "yelk", "belanchak", "kema", "mashina", "poyezd",
    "samalyot", "velik", "yo‘l", "ko‘prik", "ariq", "daryo", "ko‘l", "deniz", "tosh", "tep",
    "tog", "qir", "dala", "o‘rmon", "yaylov", "tabaqat", "yashil", "sariq", "qizil", "moviy",
    "kul", "oq", "qora", "yaxshi", "yaman", "katta", "kichik", "baland", "past", "tez",
    "sekin", "sokin", "sovuq", "issiq", "shirin", "achchiq", "yumshak", "qattiq", "yangi", "eski",
    "saxiy", "xasis", "mehr", "sev", "kul", "yigla", "yur", "yugur", "o‘yna", "ishla",
    "qara", "tingla", "yaz", "o‘qi", "ayt", "gapir", "qichqir", "chaqir", "kut", "kel",
    "bor", "chiq", "kirit", "aylan", "och", "yop", "ol", "ber", "tashla", "ushla",
    "yashir", "ko‘tar", "tushir", "qur", "yopish", "yozish", "ko‘rish", "sezish", "his", "ishon",
    "kuldir", "yig‘lat", "ur", "tep", "turt", "bos", "sil", "aylan", "yurak", "yo‘lchi",
    "yo‘lbars", "eshak", "it", "mushuk", "qush", "tovuq", "sigir", "ot", "eshon", "ari",
    "asalari", "baliq", "kapalak", "chuvalchang", "ariqcha", "guldasta", "bargcha", "uchish", "parvoz", "sayohat",
    "dunyo", "xalq", "millat", "til", "yurt", "vatan", "bayrak", "madhiya", "ona", "ata",
    "mehribon", "sadoqat", "do‘st", "dushman", "tinchlik", "urush", "baxt", "baxtsiz", "kulgu", "qahqaha",
    "tashvish", "xursand", "quvonch", "sevgi", "tuygi", "umid", "sham", "nur", "yor", "do‘kon",
    "bozor", "pul", "narx", "ish", "kasb", "usta", "talim", "fan", "savol", "javab"
    "raqam", "sanash", "hisob", "miqdar", "tartib", "navbat", "sinf", "ta’lim", "fan", "ilm",
"bilim", "kitabcha", "dastur", "kompyuter", "ekran", "sichqon", "klaviatura", "monitor", "fayl", "papka",
"ruxsat", "parol", "ism", "familiya", "manzil", "raqamcha", "telefon", "qisqa", "uzun", "eni",
"balandlik", "chuqurlik", "yumshak", "qattiq", "tekis", "notekis", "silliq", "xiralash", "yorqin", "tiniq",
"sovun", "shampun", "suvlik", "cho‘milish", "tishlab", "yuvish", "artish", "tozalash", "yaltirash", "kir",
"tufli", "etik", "shim", "kofta", "futbolka", "kurtka", "shapka", "paypoq", "ko‘ylak", "tasma",
"kamar", "soatband", "sumkach", "ko‘zoynak", "taqinchoq", "uzuk", "sirga", "zanjir", "bilakuzuk", "soch",
"sochli", "sochqaychi", "sochiq", "tarash", "yuv", "art", "kiy", "ech", "ber", "ol",
"kut", "kel", "chiq", "qayt", "qarshi", "tashla", "usla", "aylan", "yur", "yugur",
"otir", "tur", "yot", "ishla", "o‘qi", "yoz", "rasm", "bo‘ya", "kes", "qur",
"ta’mirla", "to‘la", "bo‘shat", "ko‘tar", "tushir", "bos", "sil", "ur", "tep", "turt",
"chaqir", "javab", "savol", "o‘rgan", "takror", "esla", "unut", "yordam", "bo‘l", "yashir",
"izla", "top", "yo‘qot", "qidir", "ayt", "gapir", "tingla", "kul", "yigla", "xursand",
"hayron", "xafa", "baxt", "quvonch", "umid", "orzu", "niyat", "sevgi", "mehr", "sadoqat",
"do‘st", "dushman", "yordamchi", "rahbar", "xizmat", "ishchi", "usta", "shifakar", "o‘qituvchi", "haydovchi",
"bog‘bon", "dizayner", "dasturchi", "muhandis", "dekan", "rektar", "rahbar", "boshliq", "direktor", "muallif",
"ijod", "asar", "kitab", "maqala", "she’r", "roman", "film", "serial", "lavha", "kadr",
"sahn", "rol", "aktyor", "reja", "kamera", "mikrafon", "studia", "musiqa", "ashula", "navo",
"san’at", "surat", "rang", "forma", "tasvir", "chizma", "eskiz", "tayyorla", "yozuv", "so‘z",
"gap", "jumla", "matn", "parcha", "ifoda", "fikr", "xulosa", "tasdiq", "rad", "tasavvur",
"tasir", "sabab", "natija", "tartib", "yo‘nalish", "masala", "yechim", "savdo", "bozor", "do‘kon",
"narx", "pul", "kredit", "qarz", "ishlab", "sot", "ol", "ber", "almash", "tejash",
"topish", "yo‘qotish", "foyda", "zarar", "daraja", "muvaffaqiyat", "g‘alaba", "yutuq", "yordam", "mashq",
"sport", "futbol", "tennis", "voleybol", "basketbol", "yugurish", "sakrash", "suzish", "kurash", "musobaqa",
"jamoa", "rahbar", "kapitan", "murabbiy", "tribuna", "maydan", "stadion", "tomoshabin", "qo‘llov", "raqib",
"ball", "hisob", "raqam", "teng", "yutdi", "yutqazdi", "natija", "bayram", "tug‘ilgan", "sana",
"ta’rif", "sharh", "maqta", "tanqid", "ayb", "xato", "to‘g‘ri", "noto‘g‘ri", "tasdiq", "yo‘nal",
"ko‘rsat", "belgi", "nishon", "ramz", "bayrak", "madhiya", "vatan", "yurt", "xalq", "millat",
"shahar", "qishlaq", "mahalla", "ko‘cha", "uy", "xonadon", "bino", "darvoza", "tom", "hovli",
"devor", "parda", "pol", "tavan", "deraza", "oyna", "eshik", "zamin", "yo‘lak", "burchak",
"xona", "yotoqxona", "oshxona", "mehmonxona", "kitabxona", "sinfxona", "ofis", "maktab", "institut", "universitet",
"kasalxona", "shifoxona", "apteka", "klinik", "dorixona", "laboratoriya", "tajriba", "ilmiy", "sinov", "dasturiy",
"komanda", "robot", "suniy", "intellekt", "aql", "idrok", "fikrlash", "his", "ko‘rish", "eshitish",
"hid", "ta’m", "sezgi", "qo‘l", "oyaq", "bosh", "yuz", "ko‘z", "burun", "quloq",
"til", "tish", "soch", "yurak", "qalb", "ruh", "dil", "mavzu", "narsa", "buyum",
"jihoz", "asbob", "uskun", "mexanizm", "detal", "qism", "shnur", "sim", "tok", "elektr",
"batareya", "yoritish", "chiroq", "lamp", "nur", "soya", "qorayish", "yorish", "kun", "tun",
"ertalab", "kechqurun", "yarim", "soat", "vaqt", "muddat", "uzunlik", "masafa", "tezlik", "yo‘lchi",
"manzil", "yo‘nalish", "tugash", "boshlanish", "davr", "jarayon", "holat", "vaziyat", "shart", "maqsad",
"reja", "yozuv", "bayon", "hikmat", "so‘rov", "buyruq", "iltimos", "javob", "savol", "tasdiq",
"ha", "yo‘q", "balki", "lekin", "ammo", "shunda", "keyin", "so‘ng", "birinchi", "oxirgi",
"oraliq", "o‘rta", "yuqori", "past", "katta", "kichik", "uzun", "qisqa", "yangi", "eski",
"tez", "sekin", "sokin", "sovuq", "issiq", "yumshak", "qattiq", "og‘ir", "yengil", "toza",
"iflos", "tiniq", "xiralash", "yaxshi", "yaman", "ajoyib", "g‘alati", "qiziq", "zerikarli", "hayratli",
"tasirli", "kutilmagan", "sokin", "jim", "shovqin", "baland", "past", "keng", "tor", "bo‘sh",
"to‘la", "yopiq", "ochiq", "qarshi", "teskari", "bir", "ikki", "uch", "turt", "besh",
"alt", "yetti", "sakiz", "tuqqiz", "on", "yuz", "ming", "million", "birinchi", "ikkinchi",
"uchinchi", "turtinchi", "beshinchi", "altinchi", "yettinchi", "sakkinchi", "tuqqizinchi", "oninchi", "sonli", "raqamli",
"miqdor", "ulush", "foiz", "nisbat", "daraja", "sath", "balandlik", "og‘irlik", "hajm", "mass",
"yordam", "hissa", "taklif", "fikr", "bahs", "muammo", "yechim", "yo‘l", "maqsad", "reja",
"amal", "harakat", "natija", "tajriba", "sinov", "muvaffaqiyat", "yutuq", "mashq", "o‘yin", "dam",
"sayr", "ta’til", "bayram", "marosim", "tadbir", "uchrashuv", "mehmon", "suhbat", "kulgu", "hazil"
"avval", "bahra", "yetti", "shirin", "tinch", "sokin", "yil", "barcha", "tez", "baland",
"sochiq", "ishchi", "saboq", "ilmiy", "bilim", "farzand", "ona", "aka", "uka", "singil",
"qiz", "yigit", "bola", "katta", "kichik", "mehr", "samimiy", "kulish", "yashil", "sariq",
"qizil", "ko‘k", "qalam", "daftar", "kitob", "raqam", "yuz", "ming", "bir", "ikki", "uch",
"to‘rt", "besh", "olti", "yetti", "sakkiz", "to‘qqiz", "o‘n", "yigirma", "ellik", "yuzlab",
"kecha", "kunduz", "yil", "asr", "oy", "hafta", "shanba", "yakshanba", "dushanba", "seshanba",
"chorshanba", "payshanba", "juma", "dam", "ish", "ta’til", "maktab", "sinf", "doska", "stul",
"parta", "o‘qituvchi", "talaba", "ustoz", "sinfda", "kitobxona", "ilm", "fan", "matematika",
"tarix", "adabiyot", "til", "ona", "vatan", "xalq", "millat", "bayram", "navro‘z", "mustaqil",
"ozod", "erkin", "yangi", "eski", "yaxshi", "yomon", "mehrli", "achchiq", "shirin", "suv",
"choy", "non", "meva", "sabzi", "kartoshka", "guruch", "tuxum", "asal", "sut", "qaynatma",
"sho‘rva", "palov", "lag‘mon", "kabob", "shashlik", "smetana", "qatiq", "salat", "yog‘", "nonushta",
"tushlik", "kechki", "taom", "mehmon", "uy", "xona", "oshxona", "yotoqxona", "devor", "deraza",
"eshik", "tom", "hovli", "yo‘lak", "pol", "gilam", "divan", "kreslo", "stol", "soat", "fonar",
"svet", "elektr", "tok", "kabel", "kompyuter", "telefon", "planshet", "klaviatura", "sichqoncha",
"monitor", "ekran", "kamera", "rasm", "surat", "film", "kino", "muzey", "teatr", "ashula",
"musiqa", "qo‘shiq", "san’at", "she’r", "drama", "rom", "qissa", "hikoya", "ertak", "yulduz",
"osmon", "quyosh", "oy", "yomg‘ir", "shamol", "qum", "tog‘", "daraxt", "barg", "meva", "gul",
"lola", "chaman", "ko‘l", "daryo", "ariq", "suvo‘t", "tosh", "qush", "mushuk", "it", "sigir",
"qo‘y", "echki", "ot", "eshak", "bo‘ri", "tulki", "quyon", "kabutar", "chumchuq", "ari", "kapalak",
"hasharot", "baliq", "suvlik", "dengiz", "ko‘prik", "yo‘l", "avtobus", "mashina", "velosiped",
"poezd", "samolyot", "aeroport", "stansiya", "yo‘lovchi", "haydovchi", "yo‘riq", "belgi", "xarita",
"yo‘nalish", "uychi", "ishchi", "dehqon", "ustasi", "duradgor", "temirchi", "tikuvchi", "sartarosh",
"hayvon", "yovvoyi", "uy", "ov", "shahar", "qishloq", "tuman", "viloyat", "respublika", "davlat",
"bayroq", "gerb", "madhiya", "prezident", "xalq", "rahbar", "rahmat", "iltimos", "salom", "xayr",
"marhamat", "iltifot", "hurmat", "do‘st", "yordam", "mehribon", "halol", "pok", "odam", "inson",
"erkak", "ayol", "bolalik", "ota", "ona", "aka", "uka", "opa", "singil", "qarindosh", "do‘stlik",
"baxt", "shodlik", "sevgi", "orzu", "umid", "intilish", "ishonch", "mehnat", "sadoqat", "sabru",
"qanoat", "tinchlik", "adolat", "haqiqat", "saxiylik", "mardlik", "vatanparvar", "milliy", "madaniyat",
"til", "urug‘", "tarix", "avlod", "ajdod", "xizmat", "safar", "ta’lim", "tarbiya", "yozuv", "harf",
"raqam", "belgi", "kitob", "dars", "savol", "javob", "mashq", "imtihon", "baholash", "o‘yin", "sayohat",
"dam", "yugurish", "yurish", "turgan", "ketdi", "keldi", "bor", "yo‘q", "bo‘ldi", "edi", "ekan", "kelajak",
"hozir", "kecha", "bugun", "ertangi", "bahor", "yoz", "kuz", "qish", "sovuq", "issiq", "shamol", "yomg‘ir",
"qor", "muz", "sham", "yorug‘lik", "tush", "tong", "kech", "safar", "turarjoy", "xonadon", "hovuz",
"dehqon", "ustoz", "talaba", "o‘quvchi", "tarmoq", "internet", "sayt", "dastur", "ilova", "server",
"parol", "login", "ma’lumot", "xat", "xabar", "post", "status", "so‘rov", "javob", "suhbat", "video",
"audio", "tasvir", "media", "fayl", "papka", "dasturchi", "kod", "til", "algoritm", "funksiya",
"server", "xizmat", "bot", "tarmoq", "admin", "menejer", "loyiha", "fayl", "tizim", "mijoz",
"foydalanuvchi", "hisob", "balans", "parol", "kredit", "bank", "pul", "karta", "hisob", "do‘kon",
"sotuv", "bozor", "narx", "arzon", "qimmat", "tovar", "mijoz", "buyurtma", "to‘lov", "kirim", "chiqim",
"daromad", "foyda", "ishlab", "chiqarish", "sanoat", "zavod", "fabrika", "ishlabchiqaruvchi", "texnika",
"asbob", "mexanizm", "qurol", "moslama", "robot", "sun’iy", "aqlli", "mexanik", "elektron", "raqamli",
"mobil", "dastur", "tizim", "bazaviy", "platforma", "model", "sensor", "kamera", "dron", "raketa",
"uchuvchi", "parvoz", "tezlik", "balandlik", "quvvat", "energiya", "yorug‘lik", "zaryad", "tok", "batareya",
"tarmoq", "kabinet", "ofis", "direktor", "boshliq", "xodim", "rahbar", "ishchi", "smeta", "reja", "hisob",
"natija", "maqsad", "dastur", "loyiha", "vazifa", "muddat", "yo‘nalish", "ta’sir", "baholash", "samaradorlik",
"amal", "harakat", "jarayon", "yo‘l", "natija", "ma’no", "shakl", "mazmun", "sifat", "miqdor", "nisbat",
"taqqoslash", "farq", "birlik", "juftlik", "ko‘plik", "son", "tartib", "aniq", "noaniq", "ifoda", "fikr",
"so‘z", "gap", "ibora", "jumla", "tilshunos", "yozuvchi", "muallif", "adabiyotchi", "shoir", "san’atkor",
"rejissyor", "aktyor", "muallim", "shifokor", "hamshira", "bemar", "kasal", "dori", "davolash", "shifoxona",
"apteka",  "salomat", "tibbiy", "jarroh", "ko‘rik", "tahlil", "rentgen", "vaktsina", "emlash",
"himoya", "niqob", "dezinfeksiya", "tozalash", "gigiyena", "tinchlik", "xavfsizlik", "qonun", "tartib",
"huquq", "majburiyat", "javobgarlik", "burch", "adolat", "erkinlik", "tenglik", "hurmat", "vijdon", "mas’uliyat",
"iymon", "e’tiqod", "axloq", "odamiylik", "sadoqat", "vatanparvarlik", "fidoyilik", "halollik", "saxovat",
"mehnatsevarlik", "ilmsevarlik", "ozoda", "pishiq", "sergak", "tashabbuskor", "ishchan", "do‘stona",
"mehribon", "xushmuomala", "yordamchi", "samimiy", "ochiq", "tabassum", "kulgu", "baxtiyor", "xursand",
"shod", "quvonch", "sokin", "tinch", "xotirjam", "orasta", "ozoda", "pokiza", "tartibli", "mas’ul",
"ehtiyotkor", "mehrli", "saxiy", "aqlli", "tushunarli", "o‘ylovchi", "tahlilchi", "baholovchi", "o‘rganuvchi",
"izlanuvchan", "ijodkor", "yangiliksevar", "o‘qimishli", "bilimli", "aqidaparast", "dono",  "fikrli",
"faol", "mehnatsevar", "vatanparvar", "xalqparvar", "insonparvar", "mard", "jasur", "botir", "qat’iy", "dadil",
"ishonchli", "sodiq", "sadoqatli", "barqaror", "mustahkam", "tinch", "baxtli", "ozod", "erkin"
]
