eng_translate = {

    "hello" : "salom",
    "friend" : "do'st",
    "ability": "qobiliyat",
    "able": "qodir",
    "about": "haqida",
    "above": "yuqorida",
    "accept": "qabul qilmoq",
    "according": "ko‘ra",
    "account": "hisob",
    "across": "bo‘ylab",
    "act": "harakat qilmoq",
    "action": "harakat",
    "activity": "faoliyat",
    "actually": "aslida",
    "add": "qo‘shmoq",
    "address": "manzil",
    "administration": "boshqaruv",
    "admit": "tan olmoq",
    "adult": "kattalar",
    "affect": "ta’sir qilmoq",
    "after": "keyin",
    "again": "yana",
    "against": "qarshi",
    "age": "yosh",
    "agency": "agentlik",
    "ago": "oldin",
    "agree": "rozi bo‘lmoq",
    "air": "havo",
    "all": "hamma",
    "allow": "ruxsat bermoq",
    "almost": "deyarli",
    "alone": "yolg‘iz",
    "along": "bo‘ylab",
    "already": "allaqachon",
    "also": "ham",
    "although": "garchi",
    "always": "doim",
    "american": "amerikalik",
    "among": "orasida",
    "amount": "miqdor",
    "analysis": "tahlil",
    "and": "va",
    "animal": "hayvon",
    "another": "yana bir",
    "answer": "javob",
    "any": "har qanday",
    "anyone": "kimdir",
    "anything": "nimadir",
    "appear": "paydo bo‘lmoq",
    "apply": "ariza bermoq",
    "area": "hudud",
    "argue": "bahslashmoq",
    "arm": "qo‘l",
    "around": "atrofida",
    "arrive": "yetib kelmoq",
    "art": "san’at",
    "article": "maqola",
    "artist": "san’atkor",
    "as": "kabi",
    "ask": "so‘ramoq",
    "assume": "faraz qilmoq",
    "at": "da",
    "attack": "hujum",
    "attention": "e’tibor",
    "attorney": "advokat",
    "audience": "tomoshabin",
    "author": "muallif",
    "available": "mavjud",
    "avoid": "qochmoq",
    "away": "uzoqqa",

    "baby": "chaqaloq",
    "back": "orqa",
    "bad": "yomon",
    "bag": "sumka",
    "ball": "to‘p",
    "bank": "bank",
    "bar": "bar",
    "base": "asos",
    "basic": "asosiy",
    "be": "bo‘lmoq",
    "beat": "urmoq",
    "beautiful": "chiroyli",
    "because": "chunki",
    "become": "bo‘lmoq",
    "bed": "to‘shak",
    "before": "avval",
    "begin": "boshlamoq",
    "behavior": "xonish",
    "behind": "orqasida",
    "believe": "ishonmoq",
    "benefit": "foyda",
    "best": "eng yaxshi",
    "better": "yaxshiroq",
    "between": "orasida",
    "beyond": "narida",
    "big": "katta",
    "bill": "hisob",
    "billion": "milliard",
    "bit": "bo‘lak",
    "black": "qora",
    "blood": "qon",
    "blue": "ko‘k",
    "board": "doska",
    "body": "tana",
    "book": "kitob",
    "born": "tug‘ilgan",
    "both": "ikkalasi",
    "box": "quti",
    "boy": "o‘g‘il bola",
    "break": "buzmoq",
    "bring": "olib kelmoq",
    "brother": "aka/uka",
    "budget": "byudjet",
    "build": "qurmoq",
    "building": "bino",
    "business": "biznes",
    "but": "ammo",
    "buy": "sotib olmoq",
    "by": "tomonidan",

    "call": "qo‘ng‘iroq qilmoq",
    "camera": "kamera",
    "campaign": "kampaniya",
    "can": "qila olmoq",
    "cancer": "saraton",
    "candidate": "nomzod",
    "capital": "poytaxt",
    "car": "mashina",
    "card": "karta",
    "care": "g‘amxo‘rlik",
    "career": "kasb",
    "carry": "ko‘tarmoq",
    "case": "holat",
    "catch": "ushlamoq",
    "cause": "sabab",
    "cell": "hujayra",
    "center": "markaz",
    "central": "markaziy",
    "century": "asr",
    "certain": "aniq",
    "chair": "stul",
    "challenge": "qiyinchilik",
    "chance": "imkoniyat",
    "change": "o‘zgarmoq",
    "character": "xarakter",
    "charge": "to‘lov",
    "check": "tekshirmoq",
    "child": "bola",
    "choice": "tanlov",
    "choose": "tanlamoq",
    "church": "cherkov",
    "citizen": "fuqaro",
    "city": "shahar",
    "civil": "fuqarolik",
    "claim": "da’vo qilmoq",
    "class": "sinf",
    "clear": "aniq",
    "close": "yopmoq",
    "coach": "murabbiy",
    "cold": "sovuq",
    "collection": "to‘plam",
    "college": "kollej",
    "color": "rang",
    "come": "kelmoq",
    "commercial": "tijorat",
    "common": "umumiy",
    "community": "jamiyat",
    "company": "kompaniya",
    "compare": "taqqoslamoq",
    "complete": "to‘liq",
    "computer": "kompyuter",
    "concern": "tashvish",
    "condition": "shart",
    "conference": "anjuman",
    "consider": "o‘ylamoq",
    "consumer": "iste’molchi",
    "contain": "o‘z ichiga olmoq",
    "continue": "davom etmoq",
    "control": "nazorat",
    "cost": "narx",
    "could": "mumkin edi",
    "country": "mamlakat",
    "couple": "juftlik",
    "course": "kurs",
    "court": "sud",
    "cover": "yopmoq",
    "create": "yaratmoq",
    "crime": "jinoyat",
    "cultural": "madaniy",
    "culture": "madaniyat",
    "cup": "stakan",
    "current": "joriy",
    "customer": "mijoz",
    "cut": "kesmoq",

    "dad": "ota",
    "danger": "xavf",
    "dark": "qorong‘i",
    "data": "ma’lumot",
    "daughter": "qiz",
    "day": "kun",
    "dead": "o‘lik",
    "deal": "kelishuv",
    "death": "o‘lim",
    "debate": "bahs",
    "decide": "qaror qilmoq",
    "decision": "qaror",
    "deep": "chuqur",
    "degree": "daraja",
    "Democrat": "demokrat",
    "democratic": "demokratik",
    "describe": "tasvirlamoq",
    "design": "dizayn",
    "despite": "qaramasdan",
    "detail": "batafsil",
    "determine": "belgilamoq",
    "develop": "rivojlantirmoq",
    "development": "rivojlanish",
    "die": "o‘lmoq",
    "difference": "farq",
    "different": "boshqa",
    "difficult": "qiyin",
    "dinner": "kechki ovqat",
    "direction": "yo‘nalish",
    "director": "direktor",
    "discover": "kashf etmoq",
    "discuss": "muhokama qilmoq",
    "discussion": "muhokama",
    "disease": "kasallik",
    "do": "qilmoq",
    "doctor": "shifokor",
    "dog": "it",
    "door": "eshik",
    "down": "pastga",
    "draw": "chizmoq",
    "dream": "orzu",
    "drive": "haydamoq",
    "drop": "tushirmoq",
    "drug": "dori",
    "during": "davomida",

    "each": "har bir",
    "early": "erta",
    "east": "sharq",
    "easy": "oson",
    "eat": "yemoq",
    "economic": "iqtisodiy",
    "economy": "iqtisod",
    "edge": "chegara",
    "education": "ta’lim",
    "effect": "ta’sir",
    "effort": "harakat",
    "eight": "sakkiz",
    "either": "ikki variantdan biri",
    "election": "saylov",
    "else": "boshqa",
    "employee": "ishchi",
    "end": "tugash",
    "energy": "energiya",
    "enjoy": "rohatlanmoq",
    "enough": "yetarli",
    "enter": "kirmoq",
    "entire": "butun",
    "environment": "muhit",
    "especially": "ayniqsa",
    "establish": "tashkil qilmoq",
    "even": "hatto",
    "evening": "kechqurun",
    "event": "voqea",
    "ever": "hech qachon",
    "every": "har bir",
    "everyone": "hamma",
    "everything": "hamma narsa",
    "evidence": "dalil",
    "exactly": "aniq",
    "example": "misol",
    "exist": "mavjud bo‘lmoq",
    "expect": "kutmoq",
    "experience": "tajriba",
    "expert": "mutaxassis",
    "explain": "tushuntirmoq",
    "eye": "ko‘z",

    "face": "yuz",
    "fact": "fakt",
    "factor": "omil",
    "fail": "muvaffaqiyatsiz bo‘lmoq",
    "fall": "yiqilmoq",
    "family": "oila",
    "far": "uzoq",
    "fast": "tez",
    "father": "ota",
    "fear": "qo‘rquv",
    "federal": "federal",
    "feel": "his qilmoq",
    "feeling": "hissiyot",
    "few": "bir nechta",
    "field": "maydon",
    "fight": "jang qilmoq",
    "figure": "raqam",
    "fill": "to‘ldirmoq",
    "film": "kino",
    "final": "oxirgi",
    "finally": "nihoyat",
    "financial": "moliyaviy",
    "find": "topmoq",
    "fine": "yaxshi",
    "finger": "barmoq",
    "finish": "tugatmoq",
    "fire": "olov",
    "firm": "firma",
    "first": "birinchi",
    "fish": "baliq",
    "five": "besh",
    "floor": "qavat",
    "fly": "uchmoq",
    "focus": "diqqat qaratmoq",
    "follow": "ergashmoq",
    "food": "ovqat",
    "foot": "oyoq",
    "for": "uchun",
    "force": "kuch",
    "foreign": "chet ellik",
    "forget": "unutmoq",
    "form": "shakl",
    "forward": "oldinga",
    "four": "to‘rt",
    "free": "bepul",
    "friend": "do‘st",
    "from": "dan",
    "front": "old",
    "full": "to‘la",
    "fund": "jamg‘arma",
    "future": "kelajak",

    "game": "o‘yin",
    "garden": "bog‘",
    "gas": "gaz",
    "general": "umumiy",
    "generation": "avlod",
    "get": "olmoq",
    "girl": "qiz",
    "give": "bermoq",
    "glass": "stakan",
    "go": "bormoq",
    "goal": "maqsad",
    "good": "yaxshi",
    "government": "hukumat",
    "great": "zo‘r",
    "green": "yashil",
    "ground": "yer",
    "group": "guruh",
    "grow": "o‘smoq",
    "guess": "taxmin qilmoq",
    "gun": "qurol",
    "guy": "yigit",



    "hair": "soch",
    "half": "yarim",
    "hand": "qo‘l",
    "hang": "osmoq",
    "happen": "sodir bo‘lmoq",
    "happy": "baxtli",
    "hard": "qiyin",
    "have": "ega bo‘lmoq",
    "he": "u (o‘g‘il)",
    "head": "bosh",
    "health": "salomatlik",
    "hear": "eshitmoq",
    "heart": "yurak",
    "heat": "issiq",
    "heavy": "og‘ir",
    "help": "yordam bermoq",
    "her": "uning",
    "here": "bu yerda",
    "herself": "o‘zi (qiz)",
    "high": "baland",
    "him": "uni (o‘g‘il)",
    "himself": "o‘zi (erkak)",
    "his": "uning",
    "history": "tarix",
    "hit": "urmoq",
    "hold": "ushlamoq",
    "home": "uy",
    "hope": "umid",
    "horse": "ot",
    "hospital": "shifoxona",
    "hot": "issiq",
    "hotel": "mehmonxona",
    "hour": "soat",
    "house": "uy",
    "how": "qanday",
    "however": "shunga qaramay",
    "huge": "ulkan",
    "human": "inson",
    "hundred": "yuz",
    "husband": "er",

    "I": "men",
    "idea": "fikr",
    "identify": "aniqlamoq",
    "if": "agar",
    "image": "rasm",
    "imagine": "tasavvur qilmoq",
    "important": "muhim",
    "improve": "yaxshilamoq",
    "in": "ichida",
    "include": "kiritmoq",
    "increase": "ko‘paymoq",
    "indeed": "haqiqatan",
    "indicate": "ko‘rsatmoq",
    "individual": "shaxs",
    "industry": "sanoat",
    "information": "ma’lumot",
    "inside": "ichkarida",
    "instead": "o‘rniga",
    "institution": "muassasa",
    "interest": "qiziqish",
    "interesting": "qiziqarli",
    "international": "xalqaro",
    "interview": "suhbat",
    "into": "ichiga",
    "introduce": "tanishtrmoq",
    "investment": "investitsiya",
    "involve": "jalb qilmoq",
    "issue": "muammo",

    "it": "bu",
    "its": "uning",
    "itself": "o‘zini",
    
    "job": "ish",
    "join": "qo‘shilmoq",
    "just": "shunchaki",

    "keep": "saqlamoq",
    "key": "kalit",
    "kid": "bola",
    "kill": "o‘ldirmoq",
    "kind": "tur",
    "kitchen": "oshxona",
    "know": "bilmoq",

    "language": "til",
    "large": "katta",
    "last": "oxirgi",
    "late": "kech",
    "laugh": "kulmoq",
    "law": "qonun",
    "lawyer": "advokat",
    "lay": "qo‘ymoq",
    "lead": "boshqarmoq",
    "leader": "yetakchi",
    "learn": "o‘rganmoq",
    "least": "eng kami",
    "leave": "ketmoq",
    "left": "chap",
    "leg": "oyoq",
    "legal": "qonuniy",
    "less": "kamroq",
    "let": "qo‘yib yubormoq",
    "letter": "xat",
    "level": "daraja",
    "lie": "yolg‘on gapirmoq",
    "life": "hayot",
    "light": "yorug‘lik",
    "like": "yoqtirmoq",
    "line": "qator",
    "list": "ro‘yxat",
    "listen": "tinglamoq",
    "little": "kichkina",
    "live": "yashamoq",
    "local": "mahalliy",
    "long": "uzoq",
    "look": "qaramoq",
    "lose": "yo‘qotmoq",
    "loss": "yo‘qotish",
    "lot": "ko‘p",
    "love": "sevmoq",
    "low": "past",

    "machine": "mashina",
    "magazine": "jurnal",
    "main": "asosiy",
    "major": "katta",
    "make": "qilmoq",
    "man": "erkak",
    "manage": "boshqarmoq",
    "management": "boshqaruv",
    "many": "ko‘p",
    "market": "bozor",
    "marriage": "nikoh",
    "material": "material",
    "matter": "masala",
    "may": "mumkin",
    "maybe": "balki",
    "me": "meni",
    "mean": "anglatmoq",
    "measure": "o‘lchamoq",
    "media": "media",
    "medical": "tibbiy",
    "meet": "uchrashmoq",
    "member": "a’zo",
    "memory": "xotira",
    "mention": "tilga olmoq",
    "message": "xabar",
    "method": "usul",
    "middle": "o‘rta",
    "might": "ehtimol",
    "mile": "milya",
    "military": "harbiy",
    "million": "million",
    "mind": "ong",
    "minute": "daqiqа",
    "miss": " sog‘inmoq",
    "mission": "vazifa",
    "model": "model",
    "modern": "zamonaviy",
    "moment": "lahza",
    "money": "pul",
    "month": "oy",
    "more": "ko‘proq",
    "morning": "ertalab",
    "most": "eng ko‘p",
    "mother": "ona",
    "mouth": "og‘iz",
    "move": "harakatlanmoq",
    "movie": "film",
    "much": "ko‘p",
    "music": "musiqa",
    "must": "kerak",
    "my": "mening",
    "myself": "o‘zim",

    "name": "ism",
    "nation": "millat",
    "national": "milliy",
    "natural": "tabiiy",
    "nature": "tabiat",
    "near": "yaqin",
    "nearly": "deyarli",
    "necessary": "kerak",
    "need": "zarur",
    "network": "tarmoq",
    "never": "hech qachon",
    "new": "yangi",
    "news": "yangilik",
    "newspaper": "gazeta",
    "next": "keyingi",
    "nice": "yoqimli",
    "night": "tun",
    "no": "yo‘q",
    "none": "hech kim",
    "north": "shimol",
    "not": "emas",
    "note": "eslatma",
    "nothing": "hech narsa",
    "notice": "sezmoq",
    "now": "hozir",
    "number": "raqam",

    "object": "obyekt",
    "observe": "kuzatmoq",
    "occur": "ro‘y bermoq",
    "of": "ning",
    "off": "o‘chirilgan",
    "offer": "taklif qilmoq",
    "office": "ofis",
    "officer": "ofitser",
    "official": "rasmiy",
    "often": "ko‘pincha",
    "oil": "neft",
    "ok": "xop",
    "old": "eski",
    "on": "ustida",
    "once": "bir marta",
    "one": "bir",
    "only": "faqat",
    "onto": "ustiga",
    "open": "ochmoq",
    "operation": "operatsiya",
    "opportunity": "imkoniyat",
    "option": "variant",
    "or": "yoki",
    "order": "buyruq",
    "organization": "tashkilot",
    "other": "boshqa",
    "our": "bizning",
    "out": "tashqarida",
    "outside": "tashqarida",
    "over": "ustida",
    "own": "o‘z",
    "owner": "egasi",

    "page": "sahifa",
    "pain": "og‘riq",
    "paint": "bo‘yamoq",
    "paper": "qog‘oz",
    "parent": "ota-ona",
    "part": "qism",
    "partner": "hamkor",
    "party": "partiya",
    "pass": "o‘tmoq",
    "past": "o‘tmish",
    "patient": "bemor",
    "pattern": "andoza",
    "pay": "to‘lamoq",
    "peace": "tinchlik",
    "people": "odamlar",
    "per": "har",
    "perform": "ijro etmoq",
    "period": "muddat",
    "person": "shaxs",
    "personal": "shaxsiy",
    "phone": "telefon",
    "physical": "fizik",
    "picture": "rasm",
    "piece": "bo‘lak",
    "place": "joy",
    "plan": "reja",
    "plant": "o‘simlik",
    "play": "o‘ynamoq",
    "player": "o‘yinchi",
    "point": "nuqta",
    "police": "politsiya",
    "policy": "siyosat",
    "political": "siyosiy",
    "politics": "siyosat",
    "poor": "kambag‘al",
    "popular": "ommalashgan",
    "population": "aholi",
    "position": "pozitsiya",
    "positive": "ijobiy",
    "possible": "mumkin",
    "power": "kuch",
    "practice": "amaliyot",
    "prepare": "tayyorlamoq",
    "present": "hozirgi",
    "president": "prezident",
    "pressure": "bosim",
    "pretty": "chiroyli",
    "prevent": "oldini olmoq",
    "price": "narx",
    "private": "xususiy",
    "probably": "ehtimol",
    "problem": "muammo",
    "process": "jarayon",
    "produce": "ishlab chiqarish",
    "product": "mahsulot",
    "professional": "professional",
    "professor": "professor",
    "program": "dastur",
    "project": "loyiha",
    "property": "mulki",
    "protect": "himoya qilmoq",
    "prove": "isbotlamoq",
    "provide": "ta’minlamoq",
    "public": "ommaviy",
    "pull": "tortmoq",
    "purpose": "maqsad",
    "push": "itarmoq",
    "put": "qo‘ymoq",

    "quality": "sifat",
    "question": "savol",
    "quick": "tez",
    "quickly": "tezda",
    "quiet": "jim",

    "race": "poyga",
    "radio": "radio",
    "raise": "ko‘tarmoq",
    "range": "oraliq",
    "rate": "stavka",
    "rather": "ko‘proq",
    "reach": "yetmoq",
    "read": "o‘qimoq",
    "ready": "tayyor",
    "real": "haqiqiy",
    "reality": "haqiqat",
    "realize": "tushunmoq",
    "really": "haqiqatan",
    "reason": "sabab",
    "receive": "qabul qilmoq",
    "recent": "so‘nggi",
    "record": "yozib olmoq",
    "red": "qizil",
    "reduce": "kamaytirmoq",
    "reflect": "aks ettirmoq",
    "region": "mintaqa",
    "relate": "bog‘liq bo‘lmoq",
    "relationship": "munosabat",
    "religion": "din",
    "remain": "qolmoq",
    "remember": "eslamoq",
    "remove": "olib tashlamoq",
    "report": "hisobot",
    "represent": "vakillik qilmoq",
    "require": "talab etmoq",
    "research": "tadqiqot",
    "resource": "resurs",
    "respond": "javob bermoq",
    "response": "javob",
    "rest": "dam",
    "result": "natija",
    "return": "qaytmoq",
    "reveal": "oshkor qilmoq",
    "rich": "boy",
    "right": "to‘g‘ri",
    "rise": "o‘sish",
    "risk": "xavf",
    "road": "yo‘l",
    "rock": "tosh",
    "role": "rol",
    "room": "xona",
    "rule": "qoidа",
    "run": "yugurmoq",

    "safe": "xavfsiz",
    "same": "bir xil",
    "save": "saqlamoq",
    "say": "aytmoq",
    "scene": "manzara",
    "school": "maktab",
    "science": "fan",
    "scientist": "olim",
    "score": "hisob",
    "sea": "dengiz",
    "season": "fasl",
    "seat": "o‘rindiq",
    "second": "ikkinchi",
    "section": "bo‘lim",
    "security": "xavfsizlik",
    "see": "ko‘rmoq",
    "seek": "izlamoq",
    "seem": "ko‘rinmoq",
    "sell": "sotmoq",
    "send": "yubormoq",
    "senior": "katta",
    "sense": "ma’no",
    "series": "qator",
    "serious": "jiddiy",
    "serve": "xizmat qilmoq",
    "service": "xizmat",
    "set": "o‘rnatmoq",
    "seven": "yetti",
    "several": "bir nechta",
    "sex": "jins",
    "shake": "silkitmoq",
    "share": "baham ko‘rmoq",
    "she": "u (qiz)",
    "shoot": "otmoq",
    "short": "qisqa",
    "should": "kerak",
    "shoulder": "yelka",
    "show": "ko‘rsatmoq",
    "side": "tomon",
    "sign": "belgi",
    "simple": "oddiy",
    "simply": "faqat",
    "since": "dan beri",
    "sing": "kuylamoq",
    "single": "yakka",
    "sister": "opa-singil",
    "sit": "o‘tirish",
    "site": "sayt",
    "situation": "vaziyat",
    "six": "olti",
    "size": "o‘lcham",
    "skill": "ko‘nikma",
    "skin": "teri",
    "small": "kichik",
    "smile": "tabassum",
    "so": "shu sababli",
    "social": "ijtimoiy",
    "society": "jamiyat",
    "soldier": "askar",
    "some": "ba’zi",
    "somebody": "kimdir",
    "someone": "kimdir",
    "something": "nimadir",
    "sometimes": "ba’zida",
    "son": "o‘g‘il",
    "song": "qo‘shiq",
    "soon": "tez orada",
    "sort": "tur",
    "sound": "tovush",
    "source": "manba",
    "south": "janub",
    "space": "bo‘sh joy",
    "speak": "gapirmoq",
    "special": "maxsus",
    "specific": "aniq",
    "speech": "nutq",
    "spend": "sarflamoq",
    "sport": "sport",
    "spring": "bahor",
    "staff": "xodimlar",
    "stage": "sahna",
    "stand": "turmoq",
    "standard": "standart",
    "star": "yulduz",
    "start": "boshlamoq",
    "state": "shtat",
    "statement": "bayonot",
    "station": "vokzal",
    "stay": "qolmoq",
    "step": "qadam",
    "still": "hali ham",
    "stock": "aksiya",
    "stop": "to‘xtamoq",
    "store": "do‘kon",
    "story": "hikoya",
    "strategy": "strategiya",
    "street": "ko‘cha",


}

# Teskari tarjima — avtomatik hosil qilinadi
uz_translate = {v: k for k, v in eng_translate.items()}


def translate_word(word):
    word = word.lower()

    if word in eng_translate:   # Eng → Uz
        return eng_translate[word]

    if word in uz_translate:    # Uz → Eng
        return uz_translate[word]

    return "_______"  
